### ISSUE TITLE
General Look And Feel Issues

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/datamapper-ui#36]
I don't recall the designs having that dark background image, @kcbabo?  I kinda feel like it'd be better if the component just inherits the container's background instead.

**Comment by kcbabo** [comment]
Is this for data mapper?  If so, I agree.  I have some other comments about the integrated L&F - let me know if you want those here in this issue or elsewhere.

**Comment by gashcrumb** [comment]
@kcbabo yep, so far for datamapper issues I've been using this repo, so yeah, I'd raise 'em here.

**Comment by kcbabo** [comment]
Doh!  Didn't look at the repo where the issue was filed. :-)

**Comment by mattrpav** [comment]
@gashcrumb @kcbabo let us know what you think re: background image, L&F in general. If it would help, we can hop on a call to discuss as well.

**Comment by kcbabo** [comment]
So here's my first impression feedback on the integrated L&F. I expect many/all of these are known issues that are being worked, but listing them just in case:

- Fonts are inconsistent with what's used elsewhere in the iPaaS UI.
- Background image is distracting - need to have a neutral/blended background.
- Model viewer frames are not aligned to the overall UI - the source model hangs off the left side and the mapping actions frame is off to the right.
- Text used in source and model view headers (model names) do not align with text boxes.
- Creating a mapping is very slow - the edge connecting source and target takes seconds (sometimes 10+) to actually show up.
- Mapped fields do not get a visual indicator (I think this was a little blue circle)

**Comment by kcbabo** [comment]
Hey - one thing I forgot to show is that the model viewers get kind of funky when resizing the browser window.  This is related to the comment above on the model names getting misaligned.

**Comment by jbakermd** [comment]
Ok guys, I've done a little house keeping for sanity sake. Every issue mentioned above has either been fixed or moved to other issues, here's the breakdown:

*FIXED ISSUES*

- Fixed In #35:  Creating a mapping is very slow - the edge connecting source and target takes seconds (sometimes 10+) to actually show up. (from @kcbabo)

- Fixed In #35: Mapped fields do not get a visual indicator (I think this was a little blue circle) (from @kcbabo)

*MOVED ISSUES*

Background Issues (#42): 

- Background image is distracting - need to have a neutral/blended background. (from @gashcrumb)

- I don't recall the designs having that dark background image, @kcbabo? I kinda feel like it'd be better if the component just inherits the container's background instead. (from @kcbabo)

Font Issues (Moved to #43): 

- Fonts are inconsistent with what's used elsewhere in the iPaaS UI. (from @kcbabo)

Alignment Problems (Moved to #44): 

- Model viewer frames are not aligned to the overall UI - the source model hangs off the left side and the mapping actions frame is off to the right. (from @kcbabo)

- Text used in source and model view headers (model names) do not align with text boxes. (from @kcbabo)

- Model viewers get kind of funky when resizing the browser window.  (from @kcbabo)

**Comment by jbakermd** [comment]
Feel free to keep commenting on general  L&F problems here and/or in those other new issues (#42 for background issues, #43 for font issues, #44 for alignment issues). 

I'll do further house keeping as time goes on.

**Comment by jbakermd** [comment]
Closing this issue for now. Feel free to reopen it if needed.
